name: Compilar aSPICE APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Baixar código do repositório (com submódulos)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: 2. Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: 3. Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: 4. Instalar NDK e configurar local.properties
        run: |
          sdkmanager "ndk;25.2.9519653" "cmake;3.22.1"

          echo "sdk.dir=$ANDROID_HOME" > local.properties
          echo "ndk.dir=$ANDROID_HOME/ndk/25.2.9519653" >> local.properties

      - name: 5. Preparar scripts e dependências
        run: |
          chmod +x gradlew
          chmod +x download-prebuilt-dependencies.sh
          chmod +x bVNC/prepare_project.sh

          ./download-prebuilt-dependencies.sh
          ./bVNC/prepare_project.sh --skip-build libs nopath

      - name: 6. Mostrar versões
        run: |
          java -version
          ./gradlew --version

      - name: 7. Compilar APKs
        run: |
          ./gradlew clean assembleDebug \
            --stacktrace \
            --info \
            --warning-mode all

      - name: 8. Publicar APKs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aSPICE-Pro-APK
          path: |
            **/build/outputs/apk/**/*.apk
